<?php

namespace AppBundle\Repository;

/**
 * QuantityOfOneIngredientInRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuantityOfOneIngredientInRecipeRepository extends \Doctrine\ORM\EntityRepository
{
}
