<?php

namespace AppBundle\Repository;

/**
 * RecipeCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
