<?php

namespace AppBundle\Repository;

/**
 * RecipeTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeTagRepository extends \Doctrine\ORM\EntityRepository
{
}
