<?php

namespace AppBundle\Repository;

/**
 * StepRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepRecipeRepository extends \Doctrine\ORM\EntityRepository
{
}
